### PR TITLE
2-yte-CommentAPI-Controller : creating the controller for the Comment…

### PR DESCRIPTION
**Pull request by YounesTmr**
@danglotb

### CODE REVIEW

**Comment by danglotb** [comment]
Bonjour @YounesTmr, le build fail. Je ferai la review quand tu auras fixer ça.

**Comment by YounesTmr** [comment]
@danglotb have you merged the precedents prs ?

**Comment by danglotb** [comment]
I did. I think that the base branch of this pr is not updated. We have to do a merge commit or a rebase. The history is not updated automatically.

Please do as follow :

```sh
git checkout master
git pull origin master
git checkout <branch>
git rebase master
git push --force origin <branch>
```

**Comment by YounesTmr** [comment]
@danglotb Done ! it works well

**Pull request merged**
