### PR TITLE
1.3.1-pf-feat-follow v1.1 build rest api for basic FST features :

### PR DESCRIPTION
**Pull request by pfouque06**
### 1.3.1-pf-feat-follow v1.1 build rest api for basic FST features :
- create and delete FST links
- all sort of FST listing
- add notification repository

### CODE REVIEW

**Review by danglotb — COMMENTED** [review]
LGTM, but the `notificationRepository`in `FollowStateTrackerService` seems not to be used. Thus, it is better to have only one repository per service.

**Comment by danglotb** [comment]
Where are the tests? :trollface:

**Comment by pfouque06** [comment]
> LGTM

Il sera utilisé ultérieurement car la logique de la gestion des notifications n'est pas encore implémentée.

**Comment by pfouque06** [comment]
> Where are the tests? :trollface:

not yet done since it is an intermediate PR .. as you requested small PR ... therefore the code is not fully operational and some features are missing yet.

**Comment by pfouque06** [comment]
So do you approve this intermediate PR then ?

**Pull request merged**
